@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
powershell.exe -ExecutionPolicy Bypass "choco install googlechrome -y"
powershell.exe -ExecutionPolicy Bypass "choco install adobereader -y"
powershell.exe -ExecutionPolicy Bypass "choco install 7zip -y"
powershell.exe -ExecutionPolicy Bypass "choco install flashplayerplugin -y"
